### ISSUE TITLE
Is it possible to test it with emulator?

### ISSUE THREAD

**Issue by slice-mohit** [bithyve/Cktap-Demo#2]
Is it possible to test this app with Tapsigner card emulator present [here](https://github.com/coinkite/coinkite-tap-proto/tree/master/emulator)? I'm not too familiar with react native. So, have no idea if we can connect the app with UNIX socket where emulator is present. Please let me know how can we do this for testing.

**Comment by PraneethGunas** [comment]
Hey @slice-mohit, this is a stand-alone app that interacts only with the physical card over NFC. The app doesn't talk to the emulator yet.
We haven't planned to add any support for emulators but PRs are always welcomed!

Here are the links to the [Android](https://play.google.com/store/apps/details?id=com.cktap) and [iOS](https://apps.apple.com/lr/app/cktap/id1637066132) apps.

**Comment by slice-mohit** [comment]
Hey @PraneethGunas,
I don't have a physical card yet so was wondering if there is a way to communicate with emulator. I'll try to find if this is possible to connect to UNIX socket.
